### ISSUE TITLE
failed to compile descriptor-wallet

### ISSUE THREAD

**Issue by Goosie** [BP-WG/descriptor-wallet#47]
I try to create and transfer an asset by following the https://github.com/LNP-BP/nodes/blob/master/contrib/demo-rgb.sh   Because the btc-hot and btc-cold are not installed, I suppose I have to install the descriptor wallet manually. Following the installation steps in the readme I get the following error lines:
error: unused variable: `bip43`
   --> hd/src/standards.rs:227:18
    |
227 |             Some(bip43) if s.starts_with("bip43/") => match s.strip_prefix("bip43/") {
    |                  ^^^^^ help: if this is intentional, prefix it with an underscore: `_bip43`
    |
note: the lint level is defined here
   --> hd/src/lib.rs:22:34
    |
22  | #![deny(dead_code, missing_docs, warnings)]
    |                                  ^^^^^^^^
    = note: `#[deny(unused_variables)]` implied by `#[deny(warnings)]`

error: could not compile `bitcoin_hd` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `descriptor-wallet v0.8.2 (/home/adminrgb/repos/descriptor-wallet)`, intermediate artifacts can be found at `/home/adminrgb/repos/descriptor-wallet/target`

**Comment by dr-orlovsky** [comment]
I do know which way you ahve used to compile and install, but `cargo install --all-features descriptor-wallet` is working.

You probably used master, not a tagged release, and the master is frequently gets broken

**Comment by dr-orlovsky** [comment]
The master was broken, fixed in https://github.com/BP-WG/descriptor-wallet/commit/0101d154ff0b0110481d7e4891eef306c3b0b807
