### ISSUE TITLE
non-mandatory-script-verify-flag error when broadcasting tx with electrum

### ISSUE THREAD

**Issue by zoedberg** [BP-WG/descriptor-wallet#83]
I've discovered a bug while developing the rgb-integrations-tests. When broadcasting a TX I receive a `non-mandatory-script-verify-flag` error. Here some info I've gathered:
- appears when broadcasting via electrum (doesn't appear when using esplora as indexer)
- happens when the transfer type is witness
- happens when sending an asset received back, after several other transfers (including at least a blank transition)
    - if the sending wallet is **tapret** the error is `Protocol(Object {"code": Number(2), "message": String("non-mandatory-script-verify-flag (Invalid Schnorr signature)")})`
    - if the sending wallet is **opret** the error is `Protocol(Object {"code": Number(2), "message": String("non-mandatory-script-verify-flag (Signature must be zero for failed CHECK(MULTI)SIG operation)")})`
- it may be related to the fact that [descriptor-wallet is using an old rust-bitcoin version](https://github.com/BP-WG/descriptor-wallet/blob/master/Cargo.toml#L21) and/or the fact that when converting the psbt returned from the `pay` method we cast it from v2 to v0 (because of descriptor-wallet not supporting v2)

For more info on the code that triggers the issue, see the PR https://github.com/RGB-WG/rgb-integration-tests/pull/2 (using `RUST_BACKTRACE=1` it's possible to see that the error arises from the last transfer of the `transfer_loop` test)

@dr-orlovsky I know descriptor-wallet will be eventually replaced by bp-wallet, but currently there are no other libraries we can use to use RGB with tapret1st, so either we fix this or we complete work on bp-wallet to completely drop descriptor-wallet.

**Comment by dr-orlovsky** [comment]
I had four times tried to update descriptor wallet bitcoin dependency, but failed spending couple of days with no success - too many API breaking changes in bitcoin + conflicts with strict types used in descriptor wallet which were rewritten after. I will give it another try, but if I'll fail, it will be probably faster for me to complete signing in bp-wallet.

**Comment by dr-orlovsky** [comment]
I have failed updating descriptor-wallet to latest `rust-bitcoin` (it was something like 6th attempt already), so I ended up adding signing abilities to BP libraries.

Here is WIP:
- https://github.com/BP-WG/bp-core/pull/101
- https://github.com/BP-WG/bp-std/pull/31
- https://github.com/BP-WG/bp-wallet/pull/43
- https://github.com/BP-WG/bp-wallet/pull/51

~~Next I will try to add this functionality to `bp` cli to test it~~ UPD: new PR to `bp-wallet` is added above

**Comment by zoedberg** [comment]
Closing this since we can now drop descriptor-wallet, which has been deprecated in favor of bp-wallet. I've opened https://github.com/BP-WG/bp-wallet/issues/62 to track this issue (since it happens also there)
